### PR TITLE
Added settings options for inline editing and remembering type

### PR DESCRIPTION
**Pull request by ArdenKolodner**
Hi! I use your extension frequently for my math notes, and I wanted to fix a few things that have been bugging me (not flaws with the extension, just settings that help me in my usage, and that others might benefit from).

Added settings panel, added two features that would be very useful for how I use the extension and I think will be useful to others as well:
When the corresponding option is checked in settings:
inline: matrix text will not include newline characters (option disabled by default as it makes output less readable)
remember type: the last used matrix type will be selected in the dropdown on future uses of the GUI (option enabled by default as it saves time for repeated uses)

### CODE REVIEW

**Comment by ArdenKolodner** [comment]
Also, I've never done a pull request before, my sincerest apologies if I messed something up or didn't follow some procedure. Please let me know if there's anything I should fix/know for the future!

**Comment by MohrJonas** [comment]
Looks and works great! 😄
Will be included in the next release.
Thank you for your contribution 🎉

**Comment by MohrJonas** [comment]
Included as of release [1.2.0](https://github.com/MohrJonas/obsidian-matrix/releases/tag/1.2.0)

**Comment by ArdenKolodner** [comment]
Thank you! 😁
Also, I didn’t have time last night, but there are two more features I could try to add if you think they would be useful: a hotkey to open the GUI, and remembering the x- and y-dimensions as well as the matrix type (update: got bored so I wrote them anyway; since they're optional features like everything else, I'll just submit them for review)

**Pull request merged**
